insert into states (state) values ('Alabama');
insert into states (state) values ('Alaska');
insert into states (state) values ('Arizona');
insert into states (state) values ('Arkansas');
insert into states (state) values ('California');
insert into states (state) values ('Colorado');
insert into states (state) values ('Connecticut');
insert into states (state) values ('Delaware');
insert into states (state) values ('District of Columbia');
insert into states (state) values ('Florida');
insert into states (state) values ('Georgia');
insert into states (state) values ('Hawaii');
insert into states (state) values ('Idaho');
insert into states (state) values ('Illinois');
insert into states (state) values ('Indiana');
insert into states (state) values ('Iowa');
insert into states (state) values ('Kansas');
insert into states (state) values ('Kentucky');
insert into states (state) values ('Louisiana');
insert into states (state) values ('Maine');
insert into states (state) values ('Montana');
insert into states (state) values ('Nebraska');
insert into states (state) values ('Nevada');
insert into states (state) values ('New Hampshire');
insert into states (state) values ('New Jersey');
insert into states (state) values ('New Mexico');
insert into states (state) values ('New York');
insert into states (state) values ('North Carolina');
insert into states (state) values ('North Dakota');
insert into states (state) values ('Ohio');
insert into states (state) values ('Oklahoma');
insert into states (state) values ('Oregon');
insert into states (state) values ('Maryland');
insert into states (state) values ('Massachusetts');
insert into states (state) values ('Michigan');
insert into states (state) values ('Minnesota');
insert into states (state) values ('Mississippi');
insert into states (state) values ('Missouri');
insert into states (state) values ('Pennsylvania');
insert into states (state) values ('Rhode Island');
insert into states (state) values ('South Carolina');
insert into states (state) values ('South Dakota');
insert into states (state) values ('Tennessee');
insert into states (state) values ('Texas');
insert into states (state) values ('Utah');
insert into states (state) values ('Vermont');
insert into states (state) values ('Virginia');
insert into states (state) values ('Washington');
insert into states (state) values ('West Virginia');
insert into states (state) values ('Wisconsin');
insert into states (state) values ('Wyoming');
