insert into gangs(state,count) values ('Alabama','81');
insert into gangs(state,count) values ('Alaska','61');
insert into gangs(state,count) values ('Arizona','71');
insert into gangs(state,count) values ('Arkansas','8');
insert into gangs(state,count) values ('California','336');
insert into gangs(state,count) values ('Colorado','35');
insert into gangs(state,count) values ('Connecticut','29');
insert into gangs(state,count) values ('Delaware','20');
insert into gangs(state,count) values ('District of Columbia','5');
insert into gangs(state,count) values ('Florida','390');
insert into gangs(state,count) values ('Georgia','73');
insert into gangs(state,count) values ('Hawaii','2');
insert into gangs(state,count) values ('Idaho','9');
insert into gangs(state,count) values ('Illinois','36');
insert into gangs(state,count) values ('Indiana','65');
insert into gangs(state,count) values ('Iowa','113');
insert into gangs(state,count) values ('Kansas','22');
insert into gangs(state,count) values ('Kentucky','12');
insert into gangs(state,count) values ('Louisiana','45');
insert into gangs(state,count) values ('Maine','20');
insert into gangs(state,count) values ('Maryland','36');
insert into gangs(state,count) values ('Massachusetts','181');
insert into gangs(state,count) values ('Michigan','75');
insert into gangs(state,count) values ('Minnesota','25');
insert into gangs(state,count) values ('Mississippi','17');
insert into gangs(state,count) values ('Missouri','490');
insert into gangs(state,count) values ('Montana','29');
insert into gangs(state,count) values ('Nebraska','21');
insert into gangs(state,count) values ('Nevada','11');
insert into gangs(state,count) values ('New Hampshire','25');
insert into gangs(state,count) values ('New Jersey','15');
insert into gangs(state,count) values ('New Mexico','12');
insert into gangs(state,count) values ('New York','29');
insert into gangs(state,count) values ('North Carolina','106');
insert into gangs(state,count) values ('North Dakota','4');
insert into gangs(state,count) values ('Ohio','135');
insert into gangs(state,count) values ('Oklahoma','21');
insert into gangs(state,count) values ('Oregon','20');
insert into gangs(state,count) values ('Pennsylvania','63');
insert into gangs(state,count) values ('Rhode Island','18');
insert into gangs(state,count) values ('South Carolina','104');
insert into gangs(state,count) values ('South Dakota','21');
insert into gangs(state,count) values ('Tennessee','40');
insert into gangs(state,count) values ('Texas','68');
insert into gangs(state,count) values ('Utah','30');
insert into gangs(state,count) values ('Vermont','0');
insert into gangs(state,count) values ('Virginia','92');
insert into gangs(state,count) values ('Washington','67');
insert into gangs(state,count) values ('West Virginia','5');
insert into gangs(state,count) values ('Wisconsin','67');
insert into gangs(state,count) values ('Wyoming','11');
insert into education(state,hsgrad) values ('Alabama','82,1');
insert into education(state,hsgrad) values ('Alaska','91,4');
insert into education(state,hsgrad) values ('Arizona','84,2');
insert into education(state,hsgrad) values ('Arkansas','82,4');
insert into education(state,hsgrad) values ('California','80,6');
insert into education(state,hsgrad) values ('Colorado','89,3');
insert into education(state,hsgrad) values ('Connecticut','88,6');
insert into education(state,hsgrad) values ('Delaware','87,1');
insert into education(state,hsgrad) values ('District of Columbia','87,4');
insert into education(state,hsgrad) values ('Florida','85,3');
insert into education(state,hsgrad) values ('Georgia','83,9');
insert into education(state,hsgrad) values ('Hawaii','90,4');
insert into education(state,hsgrad) values ('Idaho','88,4');
insert into education(state,hsgrad) values ('Illinois','86,4');
insert into education(state,hsgrad) values ('Indiana','86,6');
insert into education(state,hsgrad) values ('Iowa','90,5');
insert into education(state,hsgrad) values ('Kansas','89,7');
insert into education(state,hsgrad) values ('Kentucky','81,7');
insert into education(state,hsgrad) values ('Louisiana','82,2');
insert into education(state,hsgrad) values ('Maine','90,2');
insert into education(state,hsgrad) values ('Maryland','88,2');
insert into education(state,hsgrad) values ('Massachusetts','89,0');
insert into education(state,hsgrad) values ('Michigan','87,9');
insert into education(state,hsgrad) values ('Minnesota','91,5');
insert into education(state,hsgrad) values ('Mississippi','80,4');
insert into education(state,hsgrad) values ('Missouri','86,8');
insert into education(state,hsgrad) values ('Montana','90,8');
insert into education(state,hsgrad) values ('Nebraska','89,8');
insert into education(state,hsgrad) values ('Nevada','83,9');
insert into education(state,hsgrad) values ('New Hampshire','91,3');
insert into education(state,hsgrad) values ('New Jersey','87,4');
insert into education(state,hsgrad) values ('New Mexico','82,8');
insert into education(state,hsgrad) values ('New York','84,7');
insert into education(state,hsgrad) values ('North Carolina','84,3');
insert into education(state,hsgrad) values ('North Dakota','90,1');
insert into education(state,hsgrad) values ('Ohio','87,6');
insert into education(state,hsgrad) values ('Oklahoma','85,6');
insert into education(state,hsgrad) values ('Oregon','89,1');
insert into education(state,hsgrad) values ('Pennsylvania','87,9');
insert into education(state,hsgrad) values ('Rhode Island','84,7');
insert into education(state,hsgrad) values ('South Carolina','83,6');
insert into education(state,hsgrad) values ('South Dakota','89,9');
insert into education(state,hsgrad) values ('Tennessee','83,1');
insert into education(state,hsgrad) values ('Texas','79,9');
insert into education(state,hsgrad) values ('Utah','90,4');
insert into education(state,hsgrad) values ('Vermont','91,0');
insert into education(state,hsgrad) values ('Virginia','86,6');
insert into education(state,hsgrad) values ('Washington','89,7');
insert into education(state,hsgrad) values ('West Virginia','82,8');
insert into education(state,hsgrad) values ('Wisconsin','89,8');
insert into education(state,hsgrad) values ('Wyoming','91,8');
