insert into mentalillness (state, AMI) values ('Alabama',19.51);
insert into mentalillness (state, AMI) values ('Alaska',18.12);
insert into mentalillness (state, AMI) values ('Arizona',18.59);
insert into mentalillness (state, AMI) values ('Arkansas',20.0);
insert into mentalillness (state, AMI) values ('California',18.14);
insert into mentalillness (state, AMI) values ('Colorado',17.87);
insert into mentalillness (state, AMI) values ('Connecticut',16.44);
insert into mentalillness (state, AMI) values ('Delaware',19.06);
insert into mentalillness (state, AMI) values ('District of Columbia',19.32);
insert into mentalillness (state, AMI) values ('Florida',16.03);
insert into mentalillness (state, AMI) values ('Georgia',18.57);
insert into mentalillness (state, AMI) values ('Hawaii',17.04);
insert into mentalillness (state, AMI) values ('Idaho',20.81);
insert into mentalillness (state, AMI) values ('Illinois',16.37);
insert into mentalillness (state, AMI) values ('Indiana',20.25);
insert into mentalillness (state, AMI) values ('Iowa',16.83);
insert into mentalillness (state, AMI) values ('Kansas',17.56);
insert into mentalillness (state, AMI) values ('Kentucky',20.08);
insert into mentalillness (state, AMI) values ('Louisiana',19.83);
insert into mentalillness (state, AMI) values ('Maine',20.55);
insert into mentalillness (state, AMI) values ('Maryland',16.3);
insert into mentalillness (state, AMI) values ('Massachusetts',20.11);
insert into mentalillness (state, AMI) values ('Michigan',19.05);
insert into mentalillness (state, AMI) values ('Minnesota',19.65);
insert into mentalillness (state, AMI) values ('Mississippi',19.29);
insert into mentalillness (state, AMI) values ('Missouri',18.95);
insert into mentalillness (state, AMI) values ('Montana',19.76);
insert into mentalillness (state, AMI) values ('Nebraska',18.2);
insert into mentalillness (state, AMI) values ('Nevada',18.52);
insert into mentalillness (state, AMI) values ('New Hampshire',20.86);
insert into mentalillness (state, AMI) values ('New Jersey',16.27);
insert into mentalillness (state, AMI) values ('New Mexico',20.01);
insert into mentalillness (state, AMI) values ('New York',17.63);
insert into mentalillness (state, AMI) values ('North Carolina',19.33);
insert into mentalillness (state, AMI) values ('North Dakota',16.12);
insert into mentalillness (state, AMI) values ('Ohio',20.26);
insert into mentalillness (state, AMI) values ('Oklahoma',19.05);
insert into mentalillness (state, AMI) values ('Oregon',22.66);
insert into mentalillness (state, AMI) values ('Pennsylvania',17.52);
insert into mentalillness (state, AMI) values ('Rhode Island',21.6);
insert into mentalillness (state, AMI) values ('South Carolina',17.59);
insert into mentalillness (state, AMI) values ('South Dakota',16.78);
insert into mentalillness (state, AMI) values ('Tennessee',20.41);
insert into mentalillness (state, AMI) values ('Texas',16.88);
insert into mentalillness (state, AMI) values ('Utah',20.87);
insert into mentalillness (state, AMI) values ('Vermont',20.46);
insert into mentalillness (state, AMI) values ('Virginia',18.08);
insert into mentalillness (state, AMI) values ('Washington',19.76);
insert into mentalillness (state, AMI) values ('West Virginia',21.15);
insert into mentalillness (state, AMI) values ('Wisconsin',18.44);
insert into mentalillness (state, AMI) values ('Wyoming',19.14);
